[project]
name = "custom-mcps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ronnasayd", email = "ronnasayd@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.0.0",
    "pymongo>=4.0",
    "psycopg2-binary>=2.9",
    "pymysql>=1.1",
    "numpy>=1.26",
]

[project.scripts]
mongodb-mcp = "src.databases.mongodb_mcp:main"
mysql-mcp = "src.databases.mysql_mcp:main"
postgresql-mcp = "src.databases.postgresql_mcp:main"
sqlite-mcp = "src.databases.sqlite_mcp:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

